### ISSUE TITLE
ILL-Impl Tensor Term vs Type

### ISSUE THREAD

**Issue by tattymennis** [heades/ILL-Impl#10]
a (X) b is a term that can be evaluated. However, the type rules show that a (X) b : T1 (X) T2. Does the language need a Tensor type (as I have implemented TensorTy and Tensor term term in Syntax)?

**Comment by heades** [comment]
Yes, there will need to be both a tensor term and a tensor type.

**Comment by tattymennis** [comment]
Great, I have that implemented. I called our (-o) Lolly for lack of a better name. I just have Lolly and TensorTy as the only types in the language. Are there any types I'm missing?

**Comment by heades** [comment]
Yeah, you are missing I the unit type.

**Comment by tattymennis** [comment]
That's right. UnitTy has been included. This issue can be closed.

**Comment by heades** [comment]
> That's right. UnitTy has been included. This issue can be closed.
> 
> Great!  Nice work.
