### ISSUE TITLE
Property Parens in Pretty Printer

### ISSUE THREAD

**Issue by heades** [heades/ILL-Impl#14]
The output to the pretty printer will not be correct for some inputs due to parenthesization. 

For example, prettyType applied to "Lolly (Lolly I I) I" will out put "I -o I -o I", which is actually,
"I -o (I -o I)", but the correct output should be "(I -o I) -o I" which is semantically different.

So proper parens to be accounted for.

**Comment by heades** [comment]
Checkout the following for how to do this:

https://github.com/heades/gradual-typing/blob/master/impl/Pretty.hs

**Comment by tattymennis** [comment]
Work in progress.

**Comment by tattymennis** [comment]
I addressed proper parens for Lolly (if first arg is another Lolly, parenthesize), App (if first arg is another App, parenthesize), adjusted Lam (from bound var to . parenthesize).

**Comment by heades** [comment]
You said:

> App (if first arg is another App, parenthesize)

This is not needed, because (t1 t2) t3 = t1 t2 t3, because application is left associative.  

If the first argument to an application is _not_ an application or unit, then it needs to be parenthesized.
