### ISSUE TITLE
Template Haskell simplification

### ISSUE THREAD

**Issue by heades** [heades/ILL-Impl#15]
Please change:

$(derive [''Term,''Type])
instance Alpha Term
instance Alpha Type

instance Subst Term Type
instance Subst Term Term where
  isvar (Var x) = Just (SubstName x)
  isvar _ = Nothing

to the following

$(derive [''Term])
instance Alpha Term

instance Subst Term Term where
  isvar (Var x) = Just (SubstName x)
  isvar _ = Nothing

**Comment by tattymennis** [comment]
I'm having a problem with instances with that implementation. I'd like to understand more about the derive machinery instead of dumping the error. I'll bring it up on campus.

**Comment by heades** [comment]
Closing, because old way is correct.
