### ISSUE TITLE
Type of LetT and specification

### ISSUE THREAD

**Issue by tattymennis** [heades/ILL-Impl#18]
When implementing the type construction for LetT types, the typing judgment below seems to express that the type of a LetT term is type C, or constant. As per our meeting on 26 August 2016, we decided not to implement constants.

![20160909_153828](https://cloud.githubusercontent.com/assets/15022039/18440787/69f88d86-78d8-11e6-8004-5bd72107e810.jpg)

How should I handle the type of LetT terms?

**Comment by heades** [comment]
C is not a constant.  It stands for just another type.  So for example, A,B,C all stand for arbitrary types.

**Comment by tattymennis** [comment]
Ah okay, I was comparing it to the script C instead of an arbitrary type. After I update LetT, TypeCheck should be done. Can you look over my next commit to review TypeCheck.hs?

**Comment by heades** [comment]
Great news!  I will make sure and look it over in the next couple of days.  Especially before our next meeting.
