### ISSUE TITLE
Syntax data type

### ISSUE THREAD

**Issue by heades** [heades/ILL-Impl#3]

**Comment by tattymennis** [comment]
I like this issue tracker system. Should I be able to see information about the Syntax milestone? Whenever I navigate to this issue, I come back to the timeline/comment page, not to any content or information.

**Comment by tattymennis** [comment]
I suppose the Description thread would contain any information and files provided. Neat.

**Comment by heades** [comment]
Click "Issues", and then click "Milestones", and then you can see the descriptions below each milestone.  Also, don't close issues until we have both agreed that they should be closed.
